services:
  traefik:
    image: traefik:latest
    container_name: traefik_leylines
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
  leylinesmap:
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.leylines.rule=Host(`${LEYLINES_HOST}`)"
      - "traefik.http.routers.leylines.entrypoints=web"
      - "traefik.http.services.leylines.loadbalancer.server.port=3001"
